#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Birke\PinThisDay\Command\ImportCommand;
use Birke\PinThisDay\Command\ImportAllCommand;
use Birke\PinThisDay\Command\InitDbCommand;
use Symfony\Component\Console\Application;

Dotenv::load(__DIR__);

$application = new Application();
$application->add(new InitDbCommand());
$application->add(new ImportCommand());
$application->add(new ImportAllCommand());
$application->run();